In [1]:
import pandas as pd

marks = pd.Series([85, 72, 91, 68])

print(marks)

0    85
1    72
2    91
3    68
dtype: int64

In [2]:
marks = pd.Series(
    [85, 72, 91],
    index=["Aman", "Rahul", "Rohit"]
)

In [3]:
data = {
    "Name": ["Aman", "Rahul", "Rohit"],
    "Marks": [85, 72, 91],
    "Age": [20, 21, 20]
}

df = pd.DataFrame(data)

print(df)

    Name  Marks  Age
0   Aman     85   20
1  Rahul     72   21
2  Rohit     91   20

In [5]:
marks = pd.Series([10,20,30,40,50])
marks

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [7]:
marks.index

RangeIndex(start=0, stop=5, step=1)

In [9]:
marks.values

array([10, 20, 30, 40, 50])

In [10]:
marks.dtype

dtype('int64')

In [12]:
city = pd.Series([25,30,22,28],index = ['Delhi','Mumbai','Pune','Jaipur'])
city

Delhi     25
Mumbai    30
Pune      22
Jaipur    28
dtype: int64

In [15]:
data = {
    'Name':['A','B','C','D'],
    'Age':[20,21,19,20],
    'Marks':[85,72,91,68]
}

df = pd.DataFrame(data)
df

  Name  Age  Marks
0    A   20     85
1    B   21     72
2    C   19     91
3    D   20     68

In [16]:
df.shape

(4, 3)

In [17]:
df.columns

Index(['Name', 'Age', 'Marks'], dtype='object')

In [18]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [22]:
df.dtypes

Name     object
Age       int64
Marks     int64
dtype: object

In [26]:
df['Passed'] = df['Marks'] >= 40

In [27]:
df

  Name  Age  Marks  Passed
0    A   20     85    True
1    B   21     72    True
2    C   19     91    True
3    D   20     68    True

In [28]:
df['Name']

0    A
1    B
2    C
3    D
Name: Name, dtype: object

In [32]:
df[["Name", "Marks"]]

  Name  Marks
0    A     85
1    B     72
2    C     91
3    D     68

In [33]:
df.loc[len(df)] = ['E',22,65,True]

In [34]:
df

  Name  Age  Marks  Passed
0    A   20     85    True
1    B   21     72    True
2    C   19     91    True
3    D   20     68    True
4    E   22     65    True

In [35]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["A", "B", "C", "D", "E"],
    "Age": [20, 21, 19, 22, 20],
    "Marks": [85, 72, 91, 68, 95]
})

In [36]:
df.iloc[0]

Name      A
Age      20
Marks    85
Name: 0, dtype: object

In [37]:
df.iloc[2]

Name      C
Age      19
Marks    91
Name: 2, dtype: object

In [38]:
df.iloc[0:3]

  Name  Age  Marks
0    A   20     85
1    B   21     72
2    C   19     91

In [53]:
df.iloc[0,2]

np.int64(85)

In [39]:
df.iloc[2, 1]

np.int64(19)

In [40]:
df.loc[0]

Name      A
Age      20
Marks    85
Name: 0, dtype: object

In [41]:
df.loc[0, "Name"]

'A'

In [42]:
df.loc[0, ["Name", "Marks"]]

Name      A
Marks    85
Name: 0, dtype: object

In [48]:
df.iloc[0]

Name      A
Age      20
Marks    85
Name: 0, dtype: object

In [46]:
df.loc[3]

Name      D
Age      22
Marks    68
Name: 3, dtype: object

In [50]:
df["Marks"].iloc[0]

np.int64(85)

In [54]:
df['Name'].loc[4]

'E'

In [56]:
df.iloc[:3]

  Name  Age  Marks
0    A   20     85
1    B   21     72
2    C   19     91

In [58]:
df['Name'].loc[4]

'E'

In [60]:
df.loc[:2, ['Name','Marks']]

  Name  Marks
0    A     85
1    B     72
2    C     91

In [61]:
df.loc[df["Marks"] == 95]

  Name  Age  Marks
4    E   20     95