In [124]:
import numpy as np
import pandas as pd

In [125]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["A", "B", "C", "D", "E"],
    "Age": [20, 21, 19, 22, 20],
    "Marks": [85, 72, 91, 68, 95]
})

In [126]:
df['Age'].value_counts()

Age
20    2
21    1
19    1
22    1
Name: count, dtype: int64

In [127]:
df.sort_values("Marks",ascending = True)

  Name  Age  Marks
3    D   22     68
1    B   21     72
0    A   20     85
2    C   19     91
4    E   20     95

In [128]:
df.sort_values("Marks", ascending=False)

  Name  Age  Marks
4    E   20     95
2    C   19     91
0    A   20     85
1    B   21     72
3    D   22     68

In [129]:
df.sort_values("Age",ascending=True)

  Name  Age  Marks
2    C   19     91
0    A   20     85
4    E   20     95
1    B   21     72
3    D   22     68

In [130]:
df.sort_values(['Age','Marks'],ascending=[True,False])

  Name  Age  Marks
2    C   19     91
4    E   20     95
0    A   20     85
1    B   21     72
3    D   22     68

In [131]:
df['Marks'].sum()

np.int64(411)

In [132]:
df['Marks'].mean()

np.float64(82.2)

In [133]:
df['Age'].value_counts()

Age
20    2
21    1
19    1
22    1
Name: count, dtype: int64

In [134]:
df.sort_values('Marks',ascending=False).loc[:, ['Name','Marks']].head(2)

  Name  Marks
4    E     95
2    C     91

In [135]:
df.loc[df['Marks'].nlargest(2).index, ['Name','Marks']]

  Name  Marks
4    E     95
2    C     91

In [136]:
df.nlargest(2, 'Marks')[['Name', 'Marks']]

  Name  Marks
4    E     95
2    C     91

In [137]:
df.sort_values("Marks", ascending = False).head(2)[['Name','Marks']]

  Name  Marks
4    E     95
2    C     91

In [138]:
df = pd.DataFrame({
    "Name": ["A", "B", "C", "D", "E", "F"],
    "Class": ["A", "A", "B", "B", "A", "B"],
    "Marks": [85, 72, 91, 68, 95, 78]
})

In [139]:
df.groupby('Class')['Marks'].mean()

Class
A    84.0
B    79.0
Name: Marks, dtype: float64

In [140]:
df.groupby('Class')['Marks'].max()

Class
A    95
B    91
Name: Marks, dtype: int64

In [141]:
df.groupby('Class')['Marks'].sum()

Class
A    252
B    237
Name: Marks, dtype: int64

In [142]:
df.groupby('Class')['Marks'].agg(['mean','max','min'])

       mean  max  min
Class
A      84.0   95   72
B      79.0   91   68

In [143]:
df.groupby('Class')

In [144]:
df.groupby('Class')['Marks'].mean()

Class
A    84.0
B    79.0
Name: Marks, dtype: float64

In [145]:
df.loc[df.groupby('Class')['Marks'].idxmax(),['Name','Class','Marks']]

  Name Class  Marks
4    E     A     95
2    C     B     91

In [146]:
df['Marks']=df['Marks'].apply(lambda X:X+5)
df

  Name Class  Marks
0    A     A     90
1    B     A     77
2    C     B     96
3    D     B     73
4    E     A    100
5    F     B     83

In [147]:
df['Result'] = df['Marks'].apply(lambda X: 'Pass' if X >= 40 else 'Fail')
df

  Name Class  Marks Result
0    A     A     90   Pass
1    B     A     77   Pass
2    C     B     96   Pass
3    D     B     73   Pass
4    E     A    100   Pass
5    F     B     83   Pass

In [148]:
df.loc[df['Name'] == 'C', 'Marks'] -=70

In [149]:
df

  Name Class  Marks Result
0    A     A     90   Pass
1    B     A     77   Pass
2    C     B     26   Pass
3    D     B     73   Pass
4    E     A    100   Pass
5    F     B     83   Pass

In [150]:
df['Grade'] = df['Marks'].apply(
    lambda x: 'A' if x >= 90
    else 'B' if x >= 75
    else 'C' if x >= 60
    else 'D' if x >= 40
    else 'F'
)

In [151]:
df

  Name Class  Marks Result Grade
0    A     A     90   Pass     A
1    B     A     77   Pass     B
2    C     B     26   Pass     F
3    D     B     73   Pass     C
4    E     A    100   Pass     A
5    F     B     83   Pass     B

In [152]:
df['Remark'] = df['Grade'].apply(
    lambda x: 'Excellent' if x == 'A'
    else 'Good' if x == 'B'
    else 'Average' if x == 'C'
    else 'Needs Improvement' if x == 'D'
    else 'Fail'
)

In [153]:
df

  Name Class  Marks Result Grade     Remark
0    A     A     90   Pass     A  Excellent
1    B     A     77   Pass     B       Good
2    C     B     26   Pass     F       Fail
3    D     B     73   Pass     C    Average
4    E     A    100   Pass     A  Excellent
5    F     B     83   Pass     B       Good

In [154]:
df['Age'] = [20,21,18,19,22,20]

In [155]:
df['Status'] = df.apply(lambda row: 'Eligible' if (row['Marks'] >= 80) & (row['Age'] <= 20) else 'Not Eligible',axis=1)
df

  Name Class  Marks Result Grade     Remark  Age        Status
0    A     A     90   Pass     A  Excellent   20      Eligible
1    B     A     77   Pass     B       Good   21  Not Eligible
2    C     B     26   Pass     F       Fail   18  Not Eligible
3    D     B     73   Pass     C    Average   19  Not Eligible
4    E     A    100   Pass     A  Excellent   22  Not Eligible
5    F     B     83   Pass     B       Good   20      Eligible

In [156]:
df.insert(2, "Age", df.pop("Age"))

In [157]:
df

  Name Class  Age  Marks Result Grade     Remark        Status
0    A     A   20     90   Pass     A  Excellent      Eligible
1    B     A   21     77   Pass     B       Good  Not Eligible
2    C     B   18     26   Pass     F       Fail  Not Eligible
3    D     B   19     73   Pass     C    Average  Not Eligible
4    E     A   22    100   Pass     A  Excellent  Not Eligible
5    F     B   20     83   Pass     B       Good      Eligible

In [158]:
df['Extra Marks'] = [10,5,2,5,3,8]

In [159]:
df["Marks"] += df["Extra Marks"]
df

  Name Class  Age  Marks Result Grade     Remark        Status  Extra Marks
0    A     A   20    100   Pass     A  Excellent      Eligible           10
1    B     A   21     82   Pass     B       Good  Not Eligible            5
2    C     B   18     28   Pass     F       Fail  Not Eligible            2
3    D     B   19     78   Pass     C    Average  Not Eligible            5
4    E     A   22    103   Pass     A  Excellent  Not Eligible            3
5    F     B   20     91   Pass     B       Good      Eligible            8

In [160]:
df['Category'] = df.apply(
    lambda row: 'High Performer' if (row['Marks'] >= 80) & (row['Age'] <= 20) else 'Good Performer'
    if (row['Marks'] >= 60) & (row['Age'] <= 20) else 'Average',axis=1
)
df

,Name,Class,Age,Marks,Result,Grade,Remark,Status,Extra Marks,Category
0,A,A,20,100,Pass,A,Excellent,Eligible,10,High Performer
1,B,A,21,82,Pass,B,Good,Not Eligible,5,Average
2,C,B,18,28,Pass,F,Fail,Not Eligible,2,Average
3,D,B,19,78,Pass,C,Average,Not Eligible,5,Good Performer
4,E,A,22,103,Pass,A,Excellent,Not Eligible,3,Average
5,F,B,20,91,Pass,B,Good,Eligible,8,High Performer

In [161]:
df.groupby('Class')['Marks'].mean()

Class
A    95.000000
B    65.666667
Name: Marks, dtype: float64

In [162]:
df.groupby('Class')['Marks'].max()

Class
A    103
B     91
Name: Marks, dtype: int64

In [163]:
df.groupby('Class')['Marks'].min()

Class
A    82
B    28
Name: Marks, dtype: int64

In [164]:
df.groupby('Class')['Name'].count()

Class
A    3
B    3
Name: Name, dtype: int64

In [165]:
df.groupby("Class").size()

Class
A    3
B    3
dtype: int64

In [166]:
df.groupby('Class')['Marks'].sum()

Class
A    285
B    197
Name: Marks, dtype: int64

In [167]:
df.groupby('Class')['Marks'].agg(['mean','max','min','count'])

            mean  max  min  count
Class
A      95.000000  103   82      3
B      65.666667   91   28      3

In [168]:
df.groupby('Class')[['Marks','Age']].mean()

           Marks   Age
Class
A      95.000000  21.0
B      65.666667  19.0

In [169]:
df

,Name,Class,Age,Marks,Result,Grade,Remark,Status,Extra Marks,Category
0,A,A,20,100,Pass,A,Excellent,Eligible,10,High Performer
1,B,A,21,82,Pass,B,Good,Not Eligible,5,Average
2,C,B,18,28,Pass,F,Fail,Not Eligible,2,Average
3,D,B,19,78,Pass,C,Average,Not Eligible,5,Good Performer
4,E,A,22,103,Pass,A,Excellent,Not Eligible,3,Average
5,F,B,20,91,Pass,B,Good,Eligible,8,High Performer

In [170]:
df[df['Marks'] >= 90].groupby('Class').size()

Class
A    2
B    1
dtype: int64

In [171]:
df.sort_values('Marks',ascending=False).groupby('Class').first()[['Name','Marks']]

      Name  Marks
Class
A        E    103
B        F     91

In [172]:
df.groupby("Class")["Marks"].agg(["mean", "max", "min", "count"])

            mean  max  min  count
Class
A      95.000000  103   82      3
B      65.666667   91   28      3

In [173]:
df['Name'] = ['Rishabh','Amit','Kunal','Abhishek','Vansh','Khushi']

In [174]:
df

,Name,Class,Age,Marks,Result,Grade,Remark,Status,Extra Marks,Category
0,Rishabh,A,20,100,Pass,A,Excellent,Eligible,10,High Performer
1,Amit,A,21,82,Pass,B,Good,Not Eligible,5,Average
2,Kunal,B,18,28,Pass,F,Fail,Not Eligible,2,Average
3,Abhishek,B,19,78,Pass,C,Average,Not Eligible,5,Good Performer
4,Vansh,A,22,103,Pass,A,Excellent,Not Eligible,3,Average
5,Khushi,B,20,91,Pass,B,Good,Eligible,8,High Performer