In [1]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["A", "B", "C", "D", "E", "F"],
    "Class": ["A", "A", "B", "B", "A", "B"],
    "Gender": ["M", "F", "M", "F", "M", "F"],
    "Marks": [90, 77, 26, 73, 100, 83]
})

In [2]:
df.groupby("Class")["Marks"].mean()

Class
A    89.000000
B    60.666667
Name: Marks, dtype: float64

In [3]:
pd.pivot_table(
    df,
    values="Marks",
    index="Class",
    aggfunc="mean"
)

           Marks
Class
A      89.000000
B      60.666667

In [4]:
pd.pivot_table(
    df,
    values='Marks',
    index='Class',
    aggfunc='mean'
)

           Marks
Class
A      89.000000
B      60.666667

In [5]:
pd.pivot_table(
    df,
    values='Marks',
    index='Class',
    aggfunc=['mean','max']
)

            mean   max
           Marks Marks
Class
A      89.000000   100
B      60.666667    83

In [6]:
pd.pivot_table(
    df,
    values="Marks",
    index="Class",
    columns="Gender",
    aggfunc="mean"
)

Gender     F     M
Class
A       77.0  95.0
B       78.0  26.0

In [7]:
pd.pivot_table(
    df,
    values='Marks',
    index='Class',
    aggfunc='sum'
)

       Marks
Class
A        267
B        182

In [8]:
pd.pivot_table(
    df,
    values='Marks',
    index='Class',
    columns='Gender',
    aggfunc=['mean','max','count']
)

        mean       max      count
Gender     F     M   F    M     F  M
Class
A       77.0  95.0  77  100     1  2
B       78.0  26.0  83   26     2  1

In [9]:
df.groupby(["Class", "Gender"])["Marks"].agg(["mean", "max", "count"])

              mean  max  count
Class Gender
A     F       77.0   77      1
      M       95.0  100      2
B     F       78.0   83      2
      M       26.0   26      1

In [10]:
df

  Name Class Gender  Marks
0    A     A      M     90
1    B     A      F     77
2    C     B      M     26
3    D     B      F     73
4    E     A      M    100
5    F     B      F     83

In [12]:
df1 = pd.DataFrame({
    "ID": [1, 2, 3, 4],
    "Name": ["A", "B", "C", "D"],
    "Class": ["A", "A", "B", "B"],
    "Marks": [90, 80, 70, 60]
})

df2 = pd.DataFrame({
    "ID": [3, 4, 5, 6],
    "Name": ["C", "D", "E", "F"],
    "Class": ["B", "B", "C", "C"],
    "Marks": [75, 65, 88, 92]
})

In [13]:
df1

   ID Name Class  Marks
0   1    A     A     90
1   2    B     A     80
2   3    C     B     70
3   4    D     B     60

In [14]:
df2

   ID Name Class  Marks
0   3    C     B     75
1   4    D     B     65
2   5    E     C     88
3   6    F     C     92

In [17]:
pd.concat([df1,df2],ignore_index = True)

   ID Name Class  Marks
0   1    A     A     90
1   2    B     A     80
2   3    C     B     70
3   4    D     B     60
4   3    C     B     75
5   4    D     B     65
6   5    E     C     88
7   6    F     C     92

In [18]:
pd.concat([df1,df2],ignore_index=True,axis=1)

   0  1  2   3  4  5  6   7
0  1  A  A  90  3  C  B  75
1  2  B  A  80  4  D  B  65
2  3  C  B  70  5  E  C  88
3  4  D  B  60  6  F  C  92

In [19]:
pd.merge(df1,df2,on='ID')

   ID Name_x Class_x  Marks_x Name_y Class_y  Marks_y
0   3      C       B       70      C       B       75
1   4      D       B       60      D       B       65

In [20]:
pd.merge(df1,df2,on='ID',how='inner')

   ID Name_x Class_x  Marks_x Name_y Class_y  Marks_y
0   3      C       B       70      C       B       75
1   4      D       B       60      D       B       65

In [21]:
pd.merge(df1,df2,on='ID',how='outer')

   ID Name_x Class_x  Marks_x Name_y Class_y  Marks_y
0   1      A       A     90.0    NaN     NaN      NaN
1   2      B       A     80.0    NaN     NaN      NaN
2   3      C       B     70.0      C       B     75.0
3   4      D       B     60.0      D       B     65.0
4   5    NaN     NaN      NaN      E       C     88.0
5   6    NaN     NaN      NaN      F       C     92.0

In [22]:
pd.merge(df1,df2,on='ID',how='left')

   ID Name_x Class_x  Marks_x Name_y Class_y  Marks_y
0   1      A       A       90    NaN     NaN      NaN
1   2      B       A       80    NaN     NaN      NaN
2   3      C       B       70      C       B     75.0
3   4      D       B       60      D       B     65.0

In [23]:
pd.merge(df1,df2,on='ID',how='right')

   ID Name_x Class_x  Marks_x Name_y Class_y  Marks_y
0   3      C       B     70.0      C       B       75
1   4      D       B     60.0      D       B       65
2   5    NaN     NaN      NaN      E       C       88
3   6    NaN     NaN      NaN      F       C       92

In [27]:
pd.concat([df1,df2],ignore_index=True,axis=1,)

   0  1  2   3  4  5  6   7
0  1  A  A  90  3  C  B  75
1  2  B  A  80  4  D  B  65
2  3  C  B  70  5  E  C  88
3  4  D  B  60  6  F  C  92

In [30]:
pd.merge(df1,df2,on='Name',how='right')

   ID_x Name Class_x  Marks_x  ID_y Class_y  Marks_y
0   3.0    C       B     70.0     3       B       75
1   4.0    D       B     60.0     4       B       65
2   NaN    E     NaN      NaN     5       C       88
3   NaN    F     NaN      NaN     6       C       92

In [31]:
import pandas as pd

january = pd.DataFrame({
    "Name": ["A", "B", "C"],
    "Class": ["A", "A", "B"],
    "Marks": [85, 90, 72]
})

february = pd.DataFrame({
    "Name": ["D", "E", "F"],
    "Class": ["B", "A", "B"],
    "Marks": [78, 95, 88]
})

march = pd.DataFrame({
    "Name": ["G", "H", "I"],
    "Class": ["C", "C", "A"],
    "Marks": [91, 76, 89]
})

In [33]:
pd.concat([january,february,march],ignore_index=True)

  Name Class  Marks
0    A     A     85
1    B     A     90
2    C     B     72
3    D     B     78
4    E     A     95
5    F     B     88
6    G     C     91
7    H     C     76
8    I     A     89

In [34]:
df1 = pd.DataFrame({
    "ID": [1, 2, 3, 4],
    "Name": ["A", "B", "C", "D"],
    "Class": ["A", "A", "B", "B"]
})

df2 = pd.DataFrame({
    "ID": [3, 4, 5, 6],
    "Marks": [70, 60, 88, 92],
    "Grade": ["C", "D", "B", "A"]
})

In [35]:
pd.merge(
    df1,df2,
    on='ID',
    how='inner'
)

   ID Name Class  Marks Grade
0   3    C     B     70     C
1   4    D     B     60     D

In [36]:
pd.merge(
    df1,df2,
    on='ID',
    how='left'
)

   ID Name Class  Marks Grade
0   1    A     A    NaN   NaN
1   2    B     A    NaN   NaN
2   3    C     B   70.0     C
3   4    D     B   60.0     D

In [40]:
merge_df = pd.merge(
    df1,df2,
    on='ID'
)

In [41]:
merge_df[['Name','Class','Marks','Grade']]

  Name Class  Marks Grade
0    C     B     70     C
1    D     B     60     D

In [49]:
merge_df[merge_df['Marks'] >= 80]

Empty DataFrame
Columns: [ID, Name, Class, Marks, Grade]
Index: []

In [51]:
merge_df.sort_values('Marks', ascending=False)

   ID Name Class  Marks Grade
0   3    C     B     70     C
1   4    D     B     60     D

In [52]:
merge_df = pd.merge(df1, df2, on='ID')

merge_df.groupby('Class')['Marks'].mean()

Class
B    65.0
Name: Marks, dtype: float64

In [53]:
merge_df['Result'] = merge_df['Marks'].apply(lambda x: 'Pass' if x >= 40 else 'Fail')

In [54]:
merge_df

   ID Name Class  Marks Grade Result
0   3    C     B     70     C   Pass
1   4    D     B     60     D   Pass

In [55]:
merge_df[merge_df['Class'] == 'B']['Marks'].agg(
    ['max', 'min', 'mean']
)

max     70.0
min     60.0
mean    65.0
Name: Marks, dtype: float64

In [56]:
merge_df[merge_df['Class'] == 'B']['Marks'].agg(
    highest_marks='max',
    lowest_marks='min',
    average_marks='mean'
)

highest_marks    70.0
lowest_marks     60.0
average_marks    65.0
Name: Marks, dtype: float64

In [57]:
df1 = pd.DataFrame({
    "ID": [1, 2, 3, 4, 5, 6],
    "Name": ["A", "B", "C", "D", "E", "F"],
    "Class": ["A", "A", "B", "B", "A", "B"]
})

In [58]:
df2 = pd.DataFrame({
    "ID": [1, 2, 3, 4, 5, 6],
    "Marks": [90, 55, 82, 35, 76, 95]
})

In [59]:
df_m = pd.merge(df1,df2,on='ID')

In [60]:
df_m

   ID Name Class  Marks
0   1    A     A     90
1   2    B     A     55
2   3    C     B     82
3   4    D     B     35
4   5    E     A     76
5   6    F     B     95

In [61]:
df_m[df_m['Class'] == 'B']

   ID Name Class  Marks
2   3    C     B     82
3   4    D     B     35
5   6    F     B     95

In [67]:
df_m[df_m['Class']=='B'].groupby('Class')['Marks'].agg(['max','min','mean'])

       max  min       mean
Class
B       95   35  70.666667

In [69]:
df1 = pd.DataFrame({
    "ID": [1, 2, 3, 4, 5],
    "Name": ["A", "B", "C", "D", "E"],
    "Class": ["A", "A", "B", "B", "A"]
})

df2 = pd.DataFrame({
    "ID": [1, 2, 3, 4, 5],
    "Marks": [90, 65, 82, 35, 76],
    "Age": [20, 21, 19, 20, 22]
})

In [70]:
merge = pd.merge(
    df1,df2,
    on='ID'
)

In [80]:
merge[(merge['Class']=='B') & (merge['Age']<=20)].sort_values('Marks',ascending=False)[['Name','Marks','Class','Age']]

  Name  Marks Class  Age
2    C     82     B   19
3    D     35     B   20